# Generated by Django 6.0.5 on 2026-05-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('secondary_phone', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('categories', models.JSONField(blank=True, default=list, help_text='e.g. ["Gym","Fitness","Crossfit"]')),
                ('amenities', models.JSONField(blank=True, default=list, help_text='e.g. ["Parking","CCTV","WiFi"]')),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(db_index=True, max_length=100)),
                ('building_name', models.CharField(blank=True, max_length=200)),
                ('street', models.CharField(blank=True, max_length=200)),
                ('pin_code', models.CharField(blank=True, max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('instagram', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('monday_open', models.BooleanField(default=True)),
                ('monday_morning_open', models.TimeField(default='06:00')),
                ('monday_morning_close', models.TimeField(default='10:00')),
                ('monday_evening_open', models.TimeField(default='17:00')),
                ('monday_evening_close', models.TimeField(default='21:00')),
                ('tuesday_open', models.BooleanField(default=True)),
                ('tuesday_morning_open', models.TimeField(default='06:00')),
                ('tuesday_morning_close', models.TimeField(default='10:00')),
                ('tuesday_evening_open', models.TimeField(default='17:00')),
                ('tuesday_evening_close', models.TimeField(default='21:00')),
                ('wednesday_open', models.BooleanField(default=True)),
                ('wednesday_morning_open', models.TimeField(default='06:00')),
                ('wednesday_morning_close', models.TimeField(default='10:00')),
                ('wednesday_evening_open', models.TimeField(default='17:00')),
                ('wednesday_evening_close', models.TimeField(default='21:00')),
                ('thursday_open', models.BooleanField(default=True)),
                ('thursday_morning_open', models.TimeField(default='06:00')),
                ('thursday_morning_close', models.TimeField(default='10:00')),
                ('thursday_evening_open', models.TimeField(default='17:00')),
                ('thursday_evening_close', models.TimeField(default='21:00')),
                ('friday_open', models.BooleanField(default=True)),
                ('friday_morning_open', models.TimeField(default='06:00')),
                ('friday_morning_close', models.TimeField(default='10:00')),
                ('friday_evening_open', models.TimeField(default='17:00')),
                ('friday_evening_close', models.TimeField(default='21:00')),
                ('saturday_open', models.BooleanField(default=True)),
                ('saturday_morning_open', models.TimeField(default='06:00')),
                ('saturday_morning_close', models.TimeField(default='10:00')),
                ('saturday_evening_open', models.TimeField(default='17:00')),
                ('saturday_evening_close', models.TimeField(default='21:00')),
                ('sunday_open', models.BooleanField(default=False)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'gyms',
                'ordering': ['city', 'name'],
            },
        ),
    ]
